server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC #你学习mybatis时，使用的数据库地址
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
mybatis:
  type-aliases-package: cn.qi.service.pojo
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-expiration-duration-in-seconds: 10 # 10秒即过期
      lease-renewal-interval-in-seconds: 5 # 5秒一次心跳